version: '3.7'

services:
  graphql-api:
    build:
      context: ./graphql-api
    ports:
      - 3000:4000
    container_name: graphql-api
    environment:
      PORT: 3000
    volumes:
      - ./graphql-api:/workdir
      - ./graphql-api/node_modules:/workdir/node_modules

  stardew-valley-api:
    build:
      context: stardew-valley-api
    ports:
      - 3001:28848
    container_name: stardew-valley-api
    environment:
      PORT: 3001
    volumes:
      - ./stardew-valley-api:/workdir
      - ./stardew-valley-api/node_modules:/workdir/node_modules